# : Manager [[[

[mgr]
cwd = { fg = "#dee4e0" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5fbdff", bg = "#5fbdff" }
marker_cut = { fg = "#c5e7ff", bg = "#c5e7ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a9cbe2", bg = "#a9cbe2" }

# Count
count_copied = { fg = "#001e2d", bg = "#c5e7ff" }
count_cut = { fg = "#001e2d", bg = "#c5e7ff" }
count_selected = { fg = "#00382c", bg = "#a9cbe2" }

# Border
border_symbol = " "
border_style  = { fg = "#87d6bd" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#5b8a78" }
perm_read = { fg = "#2ca8ff" }
perm_write = { fg = "#3d85b5" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#1fdca1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#87d6bd", bg = "#343b38" }
progress_error = { fg = "#ffb4ab", bg = "#343b38" }

[mode]
# Mode
normal_main = { bg = "#87d6bd", fg = "#00382c", bold = true }
normal_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# Select mode
select_main = { bg = "#b2ccc2", fg = "#1d352e", bold = true }
select_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# Unset mode
unset_main = { bg = "#a9cbe2", fg = "#0e3446", bold = true }
unset_alt  = { bg = "#3f4945", fg = "#bfc9c4" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#87d6bd" }
active = { fg = "#a9cbe2", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#87d6bd" }
value = { fg = "#dee4e0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#87d6bd", bold = true, bg = "#0f1512" }
inactive = { fg = "#b2ccc2", bg = "#0f1512" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#87d6bd", bg = "#00382c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#87d6bd" }
title = {}
hovered = { fg = "#c5e7ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343b38" }
cand = { fg = "#87d6bd" }
rest = { fg = "#00382c" }
desc = { fg = "#dee4e0" }
separator = " ▶ "
separator_style = { fg = "#dee4e0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4e0" }
run = { fg = "#dee4e0" }
footer = { fg = "#1d352e", bg = "#b2ccc2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a9cbe2" }
title_warn = { fg = "#87d6bd" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dee4e0" },
    { url = "*/", fg = "#87d6bd" },
]

# : ]]]
