# : Manager [[[

[mgr]
cwd = { fg = "#dfe4dc" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#64cdea", bg = "#64cdea" }
marker_cut = { fg = "#beeaf6", bg = "#beeaf6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a2ceda", bg = "#a2ceda" }

# Count
count_copied = { fg = "#001f26", bg = "#beeaf6" }
count_cut = { fg = "#001f26", bg = "#beeaf6" }
count_selected = { fg = "#00391c", bg = "#a2ceda" }

# Border
border_symbol = " "
border_style  = { fg = "#96d5a7" }

# : ]]]


# : Status [[[

[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

# Permissions
perm_type = { fg = "#608965" }
perm_read = { fg = "#38bfe3" }
perm_write = { fg = "#418da2" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#2fda5a" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#96d5a7", bg = "#353a35" }
progress_error = { fg = "#ffb4ab", bg = "#353a35" }

[mode]
# Mode
normal_main = { bg = "#96d5a7", fg = "#00391c", bold = true }
normal_alt  = { bg = "#414942", fg = "#c0c9bf" }

# Select mode
select_main = { bg = "#b6ccb9", fg = "#223527", bold = true }
select_alt  = { bg = "#414942", fg = "#c0c9bf" }

# Unset mode
unset_main = { bg = "#a2ceda", fg = "#023640", bold = true }
unset_alt  = { bg = "#414942", fg = "#c0c9bf" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#96d5a7" }
active = { fg = "#a2ceda", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#96d5a7" }
value = { fg = "#dfe4dc" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#96d5a7", bold = true, bg = "#101510" }
inactive = { fg = "#b6ccb9", bg = "#101510" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#96d5a7", bg = "#00391c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#96d5a7" }
title = {}
hovered = { fg = "#beeaf6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a35" }
cand = { fg = "#96d5a7" }
rest = { fg = "#00391c" }
desc = { fg = "#dfe4dc" }
separator = " ▶ "
separator_style = { fg = "#dfe4dc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe4dc" }
run = { fg = "#dfe4dc" }
footer = { fg = "#223527", bg = "#b6ccb9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a2ceda" }
title_warn = { fg = "#96d5a7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dfe4dc" },
    { url = "*/", fg = "#96d5a7" },
]

# : ]]]
