-- Look and feel
-- https://wiki.hypr.land/Configuring/Variables/

-- Parse colors from the Symphony theme's colors.conf
-- This file is generated by matugen (dynamic) or shipped with static themes
local function load_colors()
    local colors = {}
    local home = os.getenv("HOME")
    local path = home .. "/.config/symphony/current/.config/hypr/theme/colors.conf"
    local f = io.open(path, "r")
    if not f then
        -- Fallback defaults
        return {
            secondary = "rgba(b6ccb9ff)",
            outline_variant = "rgba(414942ff)",
            shadow = "000000",
        }
    end

    for line in f:lines() do
        -- Match $name = rgba(value)
        local name, value = line:match("^$([%w_]+)%s*=%s*(.+)$")
        if name and value then
            colors[name] = value:gsub("%s+$", "")
        end
    end
    f:close()
    return colors
end

local colors = load_colors()

-- General
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 12,
        border_size = 2,
        col = {
            active_border = colors.secondary or "rgba(b6ccb9ff)",
            inactive_border = colors.outline_variant or "rgba(414942ff)",
        },
        resize_on_border = true,
    },
})

-- Decoration
hl.config({
    decoration = {
        rounding = 10,

        blur = {
            enabled = true,
            size = 7,
            passes = 4,
            ignore_opacity = true,
            noise = 0.0117,
            contrast = 0.8916,
            brightness = 0.8172,
            xray = false,
            popups = true,
        },

        shadow = {
            enabled = true,
            color = colors.shadow and ("rgba(" .. colors.shadow:gsub("rgba%((%x+)ff%)", "%1") .. "80)") or "rgba(00000080)",
            color_inactive = colors.shadow and ("rgba(" .. colors.shadow:gsub("rgba%((%x+)ff%)", "%1") .. "4d)") or "rgba(0000004d)",
            offset = { 2, 2 },
            range = 20,
            render_power = 3,
        },
    },
})

-- Layer rules
-- App launcher
hl.layer_rule({ match = { namespace = "rofi" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi" }, ignore_alpha = 0 })
hl.layer_rule({ match = { namespace = "rofi" }, animation = "slide bottom" })

-- Top bar
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, ignore_alpha = 0 })
hl.layer_rule({ match = { namespace = "swayosd" }, blur = true })
hl.layer_rule({ match = { namespace = "swayosd" }, ignore_alpha = 0 })

-- Notifications
hl.layer_rule({ match = { namespace = "swaync-control-center" }, blur = true })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, blur = true })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, ignore_alpha = 0 })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, ignore_alpha = 0 })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, ignore_alpha = 0.5 })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, ignore_alpha = 0.5 })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, animation = "slide right" })

-- Misc
hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = true,
        anr_missed_pings = 12,
        enable_anr_dialog = false,
        on_focus_under_fullscreen = 1,
    },
})
