-- Monitors
-- Generated by Monique — https://github.com/ToRvaLDz/monique

hl.monitor({
    output   = "desc:Beihai Century Joint Innovation Technology Co.Ltd UWQHD-144-V2",
    mode     = "3440x1440@100",
    position = "8069x552",
    scale    = 1,
    cm       = "srgb",
    sdr_min_luminance = 0.2,
    sdr_max_luminance = 80,
})

hl.monitor({
    output   = "desc:Beihai Century Joint Innovation Technology Co.Ltd UWQHD-100-C",
    mode     = "3440x1440@99.998",
    position = "4629x552",
    scale    = 1,
    cm       = "srgb",
    sdr_min_luminance = 0.2,
    sdr_max_luminance = 80,
})
