-- Auto-generated by matugen from wallpaper
-- Do not edit manually

local M = {}

M.image = "{{image}}"

<* for name, value in colors *>
M.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>

return M
